#define SCREEN_WIDTH_GAME 320
#define SCREEN_HEIGHT_GAME 240
#define SCREEN_BITDEPTH_GAME 16

#define NO_RESOLUTION_OPTION 1
//#define FULLSCREEN 1

#ifdef SDL2

#define GAME_FORCE_EXIT_BUTTON SDL_SCANCODE_ESCAPE

#define GAME_EXIT_BUTTON SDL_SCANCODE_ESCAPE
#define GAME_CONFIRM_BUTTON SDL_SCANCODE_RETURN

#define GAME_UP_BUTTON SDL_SCANCODE_UP
#define GAME_DOWN_BUTTON SDL_SCANCODE_DOWN
#define GAME_LEFT_BUTTON SDL_SCANCODE_LEFT
#define GAME_RIGHT_BUTTON SDL_SCANCODE_RIGHT

#define GAME_MISSILE_BUTTON SDL_SCANCODE_LCTRL
#define GAME_BOMB_BUTTON SDL_SCANCODE_LALT

#else

#define GAME_FORCE_EXIT_BUTTON SDLK_ESCAPE

#define GAME_EXIT_BUTTON SDLK_ESCAPE
#define GAME_CONFIRM_BUTTON SDLK_LCTRL

#define GAME_UP_BUTTON SDLK_UP
#define GAME_DOWN_BUTTON SDLK_DOWN
#define GAME_LEFT_BUTTON SDLK_LEFT
#define GAME_RIGHT_BUTTON SDLK_RIGHT

#define GAME_MISSILE_BUTTON SDLK_LCTRL
#define GAME_BOMB_BUTTON SDLK_LALT


#endif
