#define SCREEN_WIDTH_GAME 320
#define SCREEN_HEIGHT_GAME 240
#define SCREEN_BITDEPTH_GAME 16

#define NO_RESOLUTION_OPTION 1
//#define NO_FULLSCREEN 1
#define LOW_END 1

#define GAME_FORCE_EXIT_BUTTON SDLK_HOME

#define GAME_EXIT_BUTTON SDLK_LALT
#define GAME_CONFIRM_BUTTON SDLK_LCTRL

#define GAME_UP_BUTTON SDLK_UP
#define GAME_DOWN_BUTTON SDLK_DOWN
#define GAME_LEFT_BUTTON SDLK_LEFT
#define GAME_RIGHT_BUTTON SDLK_RIGHT

#define GAME_MISSILE_BUTTON SDLK_LCTRL
#define GAME_BOMB_BUTTON SDLK_LALT
